
CREATE TABLE appuser(
	UserId INT(16) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserName VARCHAR(255) NOT NULL,
	UserCreateDateTStamp DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8; 

CREATE TABLE category(
	CategoryId INT(16) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CategoryName VARCHAR(255) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE vendor(
	VendorId INT(16) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	VendorName VARCHAR(255) NOT NULL,
	VendorSite VARCHAR (5255)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE subscription(
	SubscriptionID INT(16) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserId INT(16) NOT NULL,
	CONSTRAINT fk_UserId FOREIGN KEY (UserId) REFERENCES appuser (UserId),
	Price DECIMAL(40,2) NOT NULL,
	ChargeInterval ENUM('Weekly','Monthly','Annual') NOT NULL,
	CategoryId INT(16) NOT NULL,
	CONSTRAINT fk_CategoryId FOREIGN KEY (CategoryId) REFERENCES category (CategoryId),
	VendorId INT(16) NOT NULL,
	CONSTRAINT fk_VendorId FOREIGN KEY (VendorId) REFERENCES vendor (VendorId),
	ItemOrder INT(16) NOT NULL,
	SubName VARCHAR(255),
	EntryDateTStamp DATETIME NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = utf8;
